name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # 1️⃣  Check out repo
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 2️⃣  Generate settings.js from secrets
      - name: Generate settings.js
        run: |
          cat > settings.js <<'EOF'
          window.APP_SETTINGS = {
            speechKey:       "${{ secrets.speech_key }}",
            speechRegion:    "${{ secrets.speech_region }}",
            openaiKey:       "${{ secrets.openai_key }}",
            openaiBase:      "${{ secrets.openai_base }}",
            deployment:      "${{ secrets.openai_deployment }}",
            apiVersion:      "${{ secrets.api_version }}",
            blobSasUrl:      "${{ secrets.blob_sas_url }}"
          };
          EOF
        shell: bash

      # 3️⃣  Upload to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_GLACIER_02ACFBC03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}     # for PR comments
          action: upload
          ###### Repo / Build configuration ######
          app_location: "/"          # root contains index.html
          api_location: ""           # no API
          output_location: "/"       # no build step
          ###### End of config ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_GLACIER_02ACFBC03 }}
          action: close

